"""Add start and end time for attendance

Revision ID: 544596c75e96
Revises: 63ee0e997781
Create Date: 2022-08-27 15:38:12.823034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544596c75e96'
down_revision = '63ee0e997781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_attendance_end_time'), 'attendance', ['end_time'], unique=False)
    op.create_index(op.f('ix_attendance_start_time'), 'attendance', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_start_time'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_end_time'), table_name='attendance')
    op.drop_column('attendance', 'end_time')
    op.drop_column('attendance', 'start_time')
    # ### end Alembic commands ###
