"""Add is admin to user model

Revision ID: 8bf88963b012
Revises: 544596c75e96
Create Date: 2022-08-28 18:13:42.561096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf88963b012'
down_revision = '544596c75e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_admin'), 'user', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_admin'), table_name='user')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
